### ISSUE TITLE
Can't get a job of type Pipeline to run

### ISSUE THREAD

**Issue by cgredig** [KyleLNicholls/parameterized-builds#121]
Hey there, this is propably not a bug, just a request for a little help... I am running the plugin version 3.2.1 on Bitbucket server 5.7.0 with Jenkins 2.107.1. I can't get the plugin to find my job.

I simplified the scenario as far as I could: added a hook to a repo with "manual" trigger and a job on the Jenkins root level (no subfolder). The job type is "Pipeline" using the Pipeline plugin. Although I added valid credentials to Bitbucket (both system and project level) and even tried to pass a token directly to the hook config, I always get "Job was not found".

Did I miss something? Do I have to install a special plugin in Jenkins? How can I debug further? Thanks in advance...

**Comment by a-hacker** [comment]
Hi @cgredig. You may have an issue with the Jenkins server in the project settings. I would try to trigger a `Freeform` job and see if that will work. Make sure that the url begins with either `http://` or `https://` and that there are no trailing slashes at the end. This can cause the url to become malformed when triggering the job. The next version of the the plugin will contain a `test connection` button to help track down those issues. If you are a bitbucket admin, you can pull down the master branch, create a jar, and upload the jar to get that feature early.

I say that you had made a comment in a different issue before opening this issue and mentioned toggling the `Multibranch Pipeline` checkbox. Multibranch pipelines are specific job types in Jenkins that are distinct from Pipelines and so you should not have that box checked. If you do, removing it may fix your issue.

If neither of those things fix your problem, make sure the job name is correct. It can be fairly easy to accidentally add a trailing whitespace character at the end of the job name which can mess things up. I also don't recall if job names are case sensitive or not but that could be an issue if they are.

If all else fails, try using curl to trigger the job. This plugin uses the Jenkins rest API to trigger jobs. Simply use `curl -X POST 'http://<jenkins_user>:<user_token>@<jenkins_url>/job/<job_name>/build`. If the pipeline has parameters, you can change the `build` to `buildWithParameters?<param_name>=<param_value>'`. The jenkins rest api [documentation](https://wiki.jenkins.io/display/JENKINS/Remote+access+API) is quite thorough. As are the parameterized [docs](https://wiki.jenkins.io/display/JENKINS/Parameterized+Build).

Let me know what your issue was if you figure it out. If you don't, then it would probably help if you could post some info about your settings so I can see if anything looks irregular. I hope this helps!

**Comment by cgredig** [comment]
Hi @a-hacker - thanks for your reply! I worked through your suggestions and at the end tried to curl my Jenkins and surprisingly even that returned a 404 which is propably why everything else fails. I used my own user and API token though, so not a permission problem (I am an admin on this Jenkins). Hmm. So, I guess this is not related to the parametrized-builds plugin...

**Comment by a-hacker** [comment]
Jenkins should return a 403 on permissions issues and 500 on invalid parameters so you definitely don't have those issues. 404 is pretty specific and means that Jenkins was unable to find your job.

Even if your issue doesn't relate to this plugin, I'm happy to help you debug your issue.

**Comment by cgredig** [comment]
Oh dude... I am so blind. First of all, thank you for your kind offer. Second, you were right in the beginning, it *was* a misconfiguration. Our Jenkins URL is https://jenkins.BLABLA.de/jenkins and I always forget the /jenkins at the end because, well, it looks complete without.

So, now I fixed the URL, I am trying to build a job using the token in the job's settings and I get "You do not have permissions to build this job". Is that related to the permissions in Bitbucket or Jenkins?

**Comment by a-hacker** [comment]
Setting up the jenkins settings is often more of a pain than it should be. The test button should help with that.

The permissions issue would be related to Jenkins permissions. As for your edit, do you have csrf protection enabled on your jenkins instance?

**Comment by cgredig** [comment]
Yes, I am looking forward to a test button, that will be a helpful improvement.

For the permissions, I checked and the user I entered in the plugin settings definitely has permissions to build the job.

Yes, I have CSRF protection enabled.

**Comment by a-hacker** [comment]
I just released version 3.2.3 which has that test button. The reason I asked about CSRF protection is because there was some strange behaviour with fetching the CSRF token from jenkins instances with an extra path element in the base url. Since you have the /jenkins at the end of your url, that could have caused the permissions issue. 3.2.3 should have a fix for that too. I'd recommend upgrading the plugin version and seeing if that works for you.

**Comment by cgredig** [comment]
Hi again, and thanks for the release. Current status: Test button says connection is successful. I still get "job was not found" though, for both folder/jobname and folder/"jobs"/jobname.

**Comment by Konzertheld** [comment]
@a-hacker Any more ideas? Or do you need more input from me? :)

**Comment by a-hacker** [comment]
Sorry about the delay, I've been on vacation. At this point I'm not sure what your issue could be. The "Job was not found" message should only happen on a 404 when sending the request. Since the test connection button was successful, Bitbucket can hit the Jenkins instance so there shouldn't be any weird network issues.

If I were in your shoes, I'd start simple. Try creating a new Freeform job with no parameters and not in a folder. Don't have any special settings that aren't necessary for the job and don't have it actually do anything. If you can successfully trigger that test job then piece-by-piece modify it to look more like the job you are having issues with. 

If you can't even get that test job to trigger than something else is not working correctly or causing the build url to become malformed. If this is the case and you have administer privileges on your bitbucket instance, then I'd recommend pulling down the plugin code, adding debug messages around [the code that makes the http requests](https://github.com/KyleLNicholls/parameterized-builds/blob/master/src/main/java/com/kylenicholls/stash/parameterizedbuilds/ciserver/Jenkins.java), creating a jar using maven, and then uploading that and seeing what comes up in the logs. Obviously, this is more of a last ditch effort but if you need to go this route, I can try to put together some documentation to help get you going.

Best of luck!

**Comment by Konzertheld** [comment]
@a-hacker Now I was on vacation :) Thanks again! I managed to get a freeform job at the base level running yaaay! When I put it in a folder, the message "Job not found" is back (no matter if the path is FOLDER/JOB or FOLDER/jobs/JOB). Could you say explicitly how the "Job name" field has to look like for a job in a folder when my folder is FOLDER and my job is JOB?

I can also run a job of type pipeline on the base level. So, apparently, it's the folders...

**Comment by a-hacker** [comment]
You can either use JOB or FOLDER/job/JOB as the "Job name". I'd recommend the former. Let me know if that works for you.
